In [1]:
import numpy as np

In [3]:
a = np.arange(3*3).reshape(3, 3)
print(a)
print(np.einsum('ii', a))
print(np.trace(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12
12


In [7]:
print(np.einsum('i', range(10)))

[0 1 2 3 4 5 6 7 8 9]


In [8]:
np.einsum('ij', a)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.einsum('ji', a)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])