# $p$ 次多项式空间的编号和指标的对应关系

$$
\begin{array}{rccccccccccccc}
p=0:&    &    &    &    &    &    &  1\\
p=1:&    &    &    &    &    &  x &    &  y\\
p=2:&    &    &    &    &  x^2 &    &  xy &    &  y^2\\
p=3:&    &    &    &  x^3 &    &  x^2y &    &  xy^2 &    &  y^3\\
p=4:&    &    &  x^4 &    &  x^3y &    &  x^2y^2 &    &  xy^3 &    &  y^4\\
p=5:&    &  x^5 &    &  x^4y &    & x^3y^2 &    & x^2y^3 &    &  xy^4 &    &  y^5\\
p=6:&  x^6 &    &  x^5y &    & x^4y^2 &    & x^3y^3 &    & x^2y^4 &    &  xy^5 &    &  x^6\\
\end{array}
$$

## 二维情形

二重指标　$\alpha=(a, b)$ , $\mathbf x^\alpha = x^{a}y^{b}$. $m_{\alpha}$ 是 $\alpha$ 所对应的单项式, $\nabla{m_{\alpha}}$ 是单项式的梯度, $\Delta{m_{\alpha}}$ 是单项式的拉普拉斯.

$\alpha$ 所对应的编号为:

$$
0\\
1 \qquad 2\\
3\qquad 4 \qquad 5\\
6\qquad 7 \qquad 8\qquad 9\\
10\qquad 11 \qquad 12\qquad 13\qquad 14\\
15\qquad 16 \qquad 17\qquad 18\qquad 19\qquad 20\\
\cdots\qquad \cdots\qquad \cdots\qquad \cdots\qquad \cdots\qquad \cdots\qquad\cdots\qquad
$$

$\alpha$ 所对应的二重指标为:

$$
(0,0)\\
(1,0) \qquad (0,1)\\
(2,0)\qquad (1,1) \qquad (0,2)\\
(3,0)\qquad (2,1) \qquad (1,2)\qquad (0,3)\\
(4,0)\qquad (3,1) \qquad (2,2)\qquad (1,3)\qquad (0,4)\\
(5,0)\qquad (4,1) \qquad (3,2)\qquad (2,3)\qquad (1,4)\qquad (0,5)\\
\cdots\qquad \cdots\qquad \cdots\qquad \cdots\qquad \cdots\qquad \cdots\qquad\cdots\qquad
$$

若已知 $(a,b)$, 则对应的 $\alpha$ 编号为:

$$
\alpha = \frac{(a+b)(a+b+1)}{2}+b
$$

若已知 $\alpha$, 则对应的 $(a, b)$, 计算公式为
$$
a+b = \lfloor \frac{-1+\sqrt{1+8\alpha}}{2}\rfloor\\
b = \alpha - \frac{(a+b)(a+b+1)}{2}
$$

## 三维情形

三重指标　$\alpha=(a, b, c)$ , $\mathbf x^\alpha = x^{a}y^{b}z^{c}$. $m_{\alpha}$ 是 $\alpha$ 所对应的单项式, $\nabla{m_{\alpha}}$ 是单项式的梯度, $\Delta{m_{\alpha}}$ 是单项式的拉普拉斯.

若已知 $(a,b)$, 则对应的 $\alpha$ 编号为:

$$
\alpha = \frac{(a+b+c)(a+b+c+1)(a+b+c+2)}{6}+\frac{(b+c)(b+c+1)}{2}+c
$$

若已知 $\alpha$, 则对应的 $(a, b, c)$, 计算公式为
$$
a+b+c = \left\lfloor \left(3\alpha+\frac{1}{3}\sqrt{81\alpha^2-\frac{1}{3}}\right)^{\frac{1}{3}}+\frac{1}{3\left(3\alpha+\frac{1}{3}\sqrt{81\alpha^2-\frac{1}{3}}\right)^{\frac{1}{3}}}-1\right\rfloor\\
\frac{(b+c)(b+c+1)}{2}+c = \alpha - \frac{(a+b+c)(a+b+c+1)(a+b+c+2)}{6}
$$

设 $\alpha - \frac{(a+b+c)(a+b+c+1)(a+b+c+2)}{6} = k$ ,则

$$
b+c = \lfloor \frac{-1+\sqrt{1+8k}}{2}\rfloor\\
c = k - \frac{(b+c)(b+c+1)}{2}
$$

### 三维编号的转换关系

$$
0\\
1\qquad 2\\
3\qquad 4 \qquad 5\\
$$

四面体网格的每个单元的面上局部编号和全局编号之间的关系是什么呢？ 全局编号时每个面上从第一个顶点开始按三角形的方式编号， 但每个单元内局部编号的起点可能不一致，这样需要对这个面上的全局编号重新排序。 如上图中本来的排序为：

给定四面体的一个面三个点的排序， 
$$
(i, j, k)
$$
按和这个排序进行全局自由度的编号， 现给定另一个排序

$$
(i_1, j_1, k_1)
$$

它对应一个局部自由度的排序， 其中 $(i_1, j_1, k_1)$ 的排序方向和 $(i, j, k)$ 一定不一致吗？

首先， 每个面的是从它左边单元中取出来的， 其法线方向指向左边单元的外部， 

    localFace = np.array([[1, 2, 3], [0, 3, 2]， [0, 1, 3], [0, 2, 1]])

根据每个单元中的自由度编号顺序， 它的四个面的取法：

    localFace = np.array([[1, 2, 3], [0, 2, 3], [0, 1, 3], [0, 1, 2]])
    
注意第 1 个面和第 3 个面的法向指向单元内部。

给定一个单元， 取它对应的局部编号面 $(i_1, j_1, k_1)$， 及对应的全局面 $(i, j, k)$, 分两种情况讨论：

1. 它是全局面对应的左边单元， 那么它的局部编号面要么和全局面完全一致， 要么排序相反
2. 它是全局面对应的右边单元， 则局部第 0 个面和第 2 个面一定和全局面编号相反；第 1 个和第 3 个面的排序就可能是全局面排序一个同顺序的排列


In [3]:
import numpy as np

def print_tri(p):
    print('$$','\n')
    idx = -1
    for i in range(p+1):
        idx += 1
        print(idx, end=' ')
        for j in range(1, i+1):
            idx += 1
            print('\\qquad ', idx, end=' ')
        print('\\\\', '\n')
    print('$$')
        
    
def cell_idx(p):
    ldof = int((p+1)*(p+2)/2)
    idx = np.arange(0, ldof)
    idx0 = np.floor((-1 + np.sqrt(1 + 8*idx))/2)
    idx1 = idx0*(idx0+1)/2
    cellIdx = np.zeros((ldof, 3), dtype=np.int)
    cellIdx[:,2] = idx - idx1 
    cellIdx[:,1] = idx0 - cellIdx[:,2]
    cellIdx[:,0] = p - cellIdx[:, 1] - cellIdx[:, 2] 
    return cellIdx
p = 1   
idx = cell_idx(p)
print(idx)
localIdx = np.array([
        [0, 1, 2],
        [0, 2, 1],
        [1, 0, 2],
        [1, 2, 0],
        [2, 1, 0],
        [2, 0, 1],
    ])
for i in range(6):
    I = idx[:, localIdx[i]]
    print(i,'\n', I)
    J = I[:, 1] + I[:, 2]
    print(J*(J+1)/2 +I[:, 2])
print(idx)
print_tri(p)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
0 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
[ 0.  1.  2.]
1 
 [[1 0 0]
 [0 0 1]
 [0 1 0]]
[ 0.  2.  1.]
2 
 [[0 1 0]
 [1 0 0]
 [0 0 1]]
[ 1.  0.  2.]
3 
 [[0 0 1]
 [1 0 0]
 [0 1 0]]
[ 2.  0.  1.]
4 
 [[0 0 1]
 [0 1 0]
 [1 0 0]]
[ 2.  1.  0.]
5 
 [[0 1 0]
 [0 0 1]
 [1 0 0]]
[ 1.  2.  0.]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
$$ 

0 \\ 

1 \qquad  2 \\ 

$$


In [2]:
import numpy as np
p = 2
ldof = int((p+1)*(p+2)*(p+3)/6)
idx = np.arange(1, ldof)
idx0 = (3*idx + np.sqrt(81*idx*idx - 1/3)/3)**(1/3) 
idx0 = np.floor(idx0 + 1/idx0/3 - 1 + 1e-4) # a+b+c
idx1 = idx - idx0*(idx0 + 1)*(idx0 + 2)/6
idx2 = np.floor((-1 + np.sqrt(1 + 8*idx1))/2) # b+c
cellIdx = np.zeros((ldof, 4), dtype=np.int)
cellIdx[1:, 3] = idx1 - idx2*(idx2 + 1)/2
cellIdx[1:, 2] = idx2 - cellIdx[1:, 3]
cellIdx[1:, 1] = idx0 - idx2
cellIdx[:, 0] = p - np.sum(cellIdx[:, 1:], axis=1)
print(cellIdx)

[[2 0 0 0]
 [1 1 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 2 0 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 2 0]
 [0 0 1 1]
 [0 0 0 2]]


给定两个相同形状的二维数组 `a` 和 `b`，其中 `b` 的每一行是 `a` 的对应行的一个排列， 请构造矩阵 `I`， 满足  `b = a[:, I]`

In [7]:
import numpy as np
a = np.array([
        [4, 7, 3],
        [7, 1, 8],
        [9, 3, 2],
    ])
b = np.array([
        [7, 3, 4],
        [1, 7, 8],
        [9, 2, 3],
    ])
print(a)
print(b)
idxb = np.argsort(b, axis=1)
idxb1 = np.argsort(idxb, axis=1)
idxa = np.argsort(a, axis=1)
idx = np.array([0, 1, 2]).reshape(-1, 1)
print(idxa[idx, idxb1])
print(a[idx, idxa[idx, idxb1]])
a[:, [[2, 1, 0], [1, 2, 0], [0, 1, 2]]]

[[4 7 3]
 [7 1 8]
 [9 3 2]]
[[7 3 4]
 [1 7 8]
 [9 2 3]]
[[1 2 0]
 [1 0 2]
 [0 2 1]]
[[7 3 4]
 [1 7 8]
 [9 2 3]]


array([[[3, 7, 4],
        [7, 3, 4],
        [4, 7, 3]],

       [[8, 1, 7],
        [1, 8, 7],
        [7, 1, 8]],

       [[2, 3, 9],
        [3, 2, 9],
        [9, 3, 2]]])

In [9]:
a = np.array([
        [4, 7, 3],
        [7, 1, 8],
        [9, 3, 2],
    ])

I = np.array([
        [2, 1, 0],
        [1, 2, 0],
        [0, 2, 1],
    ])

b = a[np.arange(3).reshape(-1, 1), I]
print(b)

[[3 7 4]
 [1 8 7]
 [9 2 3]]
