In [17]:
import numpy as np

def gs(A, b, x0, tol=1e-8, maxit=1000):
    L = np.tril(A)
    Linv = np.linalg.inv(L)
    U = np.triu(A, 1)
    for i in range(maxit):
        x1 = - Linv@U@x0 + Linv@b
        error = np.linalg.norm(x1 - x0)
        print(x1)
        if error < tol:
            print(i, error)
            break
        else:
            x0 = x1
            
            
A = np.array([(1, -1, 0), (-1, 2, -1), (0, -1, 1)])
epsilon = 0
I = np.eye(3)
b = np.array([-1, -1, 2])
x0 = np.zeros(3, dtype=np.float)

gs(A+epsilon*I, b, x0)

[-1. -1.  1.]
[-2. -1.  1.]
[-2. -1.  1.]
2 0.0


In [6]:
A = np.array([(1, -1, 0), (-1, 2, -1), (0, -1, 1)])
np.triu(A, 1)
np.linalg.inv(np.triu(A))

array([[ 1.        ,  0.14285714,  0.14285714],
       [ 0.        ,  0.14285714,  0.14285714],
       [ 0.        ,  0.        ,  1.        ]])